{% set name = "mkdocs-bibtex" %}
{% set version = "2.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocs-bibtex-{{ version }}.tar.gz
  sha256: 9aacb98e944c48e3f21b76e3d6774890ae7bcec347f48a323dbc7a7c63a7fa6d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools-scm
    - pip
  run:
    - python >=3.6
    - mkdocs >=1
    - pybtex >=0.22
    - pypandoc >=1.5
    - requests >=2.8.1
    - validators >=0.19.0

test:
  imports:
    - mkdocs_bibtex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/shyamd/mkdocs-bibtex/
  summary: An MkDocs plugin that enables managing citations with BibTex
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mahf708
