{% set name = "mkdocs-bibtex" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 51bf2f08950285bfda2fa1e4c9b08cb035938a61f52dfea8d8fa37fe997c05cf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - mkdocs >=1.2
    - pybtex >=0.22
    - pypandoc >=1.5
    - requests >=2.8.1
    - validators >=0.19.0
    - setuptools >=68.0.0
    - response >=0.25.6

test:
  imports:
    - mkdocs_bibtex
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/shyamd/mkdocs-bibtex/
  summary: An MkDocs plugin that enables managing citations with BibTex
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mahf708
